//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudades
    {
        public int idciudad { get; set; }
        public string Nombre { get; set; }
        public string idEstado { get; set; }
        public string IdPais { get; set; }
    }
}
