//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosTarjeta
    {
        public string noTarjeta { get; set; }
        public string Coordenada { get; set; }
        public string Dato { get; set; }
        public int iddatostarjeta { get; set; }
    }
}
