//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosticos
    {
        public int idpaciente { get; set; }
        public Nullable<int> idmedico { get; set; }
        public string Lineas { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string LineasVital { get; set; }
        public string datos { get; set; }
        public Nullable<int> idconsulta { get; set; }
        public int iddiagnostico { get; set; }
    }
}
