//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medico
    {
        public int IdRegistro { get; set; }
        public int Idmedico { get; set; }
        public Nullable<int> IdEspecialidad { get; set; }
        public string CedulaEspecialidad { get; set; }
        public string CertCMCP { get; set; }
        public string AgrupacionLocal { get; set; }
        public string AgrupacionNacional { get; set; }
        public string RFC { get; set; }
        public Nullable<byte> PediatraPlus { get; set; }
        public string CedulaProfesional { get; set; }
        public string NoRegSSA { get; set; }
        public string UniversidadEspecialidad { get; set; }
        public string HospitalResidenciaPediatra { get; set; }
        public string DomicilioConsultorio { get; set; }
        public string TelefonoConsultorio { get; set; }
        public string TelefonoFax { get; set; }
        public string NoTarjeta { get; set; }
        public string computadora { get; set; }
        public string guid { get; set; }
        public Nullable<int> recetatop { get; set; }
        public Nullable<int> recetabottom { get; set; }
        public Nullable<int> recetaleft { get; set; }
        public Nullable<int> consultatop { get; set; }
        public Nullable<int> recetaright { get; set; }
        public Nullable<int> consultabottom { get; set; }
        public Nullable<int> consultaleft { get; set; }
        public Nullable<int> consultaright { get; set; }
    }
}
