//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patologias
    {
        public string Nombre { get; set; }
        public string Fecha { get; set; }
        public string Observaciones { get; set; }
        public string Alergeno { get; set; }
        public string Manejo { get; set; }
        public string Evoluciones { get; set; }
        public Nullable<int> EdadAdquirida { get; set; }
        public Nullable<int> Categoria { get; set; }
        public string RelacionSospechosa { get; set; }
        public Nullable<int> idpaciente { get; set; }
        public int idpatologia { get; set; }
    }
}
